language: php

php:
  - 5.4

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install --prefer-source --dev --no-interaction
 - mkdir -p build/logs
 - mkdir -p build/coverage

script:
  - php vendor/bin/phpunit --bootstrap test/Bootstrap.php  --configuration test/phpunit.xml --coverage-html build/coverage/ test/